### ISSUE TITLE
width and height attributes clash with Tilegrid

### ISSUE THREAD

**Issue by mtowara** [adafruit/Adafruit_CircuitPython_ProgressBar#17]
Hi,
it seems to me that width and height return self._width and self._height of the displayio.Tilegrid  superclass, and thus alway (1,1).
Thus the library is currently broken, as progress is not calculated correctly.
I'll provide a PR shortly.

Cheers!

**Comment by brentru** [comment]
@mtowara Hi, the tilegrid docs don't seem to share the private properties of this library. It uses `width` and `height` instead of `_width` and `_height` like this library does. (https://circuitpython.readthedocs.io/en/5.0.x/shared-bindings/displayio/TileGrid.html#displayio.TileGrid)

**Comment by mtowara** [comment]
hm, then maybe its an issue with the versions on pyPI (I'm running on raspi Zero W), will check versions and come backt to you.

**Comment by mtowara** [comment]
It seems I'm using this. The circuitpython docs seem to refer to the C-bindings while this is a native Python implementation?
https://github.com/adafruit/Adafruit_Blinka_Displayio/blob/master/displayio/tilegrid.py

**Comment by FoamyGuy** [comment]
resolved by #18
