### ISSUE TITLE
Replace `assert()` calls with `if`/`else`/`raise <Exception>()`

### ISSUE THREAD

**Issue by hugodahl** [adafruit/Adafruit_CircuitPython_ProgressBar#28]
Per a conversation in the [FXAS21002C library](https://github.com/adafruit/Adafruit_CircuitPython_FXAS21002C/) on [issue #21](https://github.com/adafruit/Adafruit_CircuitPython_FXAS21002C/issues/21), checking for conditions and raising an exception is preferable over calling `assert()`. This is preferable for a number of reasons, including memory usage.

**Comment by syedmalimustafa** [comment]
Can I take this?

**Comment by jposada202020** [comment]
@alimustafashah Thanks for your interest, for sure thank you very much, that would be really appreciated. thanks :)

**Comment by syedmalimustafa** [comment]
Can you assign the task to me?

**Comment by jposada202020** [comment]
@alimustafashah if this is your first time contributing to CP
Teh following information could be helpful
code is reviewed by the CI so ths learning guide is very useful https://learn.adafruit.com/improve-your-code-with-pylint
If will facilitate things if you use pre-commit:
`pre-commit run --all-files`
And in case you change any documentation, in the docs directory built the documentation locally
`sphinx-build -E -W -b html . _build/html`

Thanks :)

**Comment by syedmalimustafa** [comment]
Thanks for sharing!

**Comment by jposada202020** [comment]
Solved by #30
