### ISSUE TITLE
Version number is missing ?

### ISSUE THREAD

**Issue by jepler** [adafruit/Adafruit_CircuitPython_ProgressBar#34]
I noticed that circup always insists the module needs updating.
```
Found 1 module[s] needing update.
Device version: None, Bundle version: None
Updated adafruit_progressbar
```
THis may be beacuse `__init__.py` doesn't have `__version__`.  The standard `__repo__` should possibly also be added.

**Comment by tekktrik** [comment]
Oh hey, refinding issues I found before!  @jepler, has this been fixed since the merged PR?
